# Generated by Django 4.0.4 on 2022-06-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mood', models.CharField(max_length=100)),
                ('quote', models.TextField(max_length=250)),
            ],
        ),
    ]
