# Generated by Django 4.0.4 on 2022-07-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_episode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.CharField(max_length=2),
        ),
    ]
