# Generated by Django 4.0.4 on 2022-07-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_location_character_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
